//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_i18n.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_7_i18n.Translation.Translate", typeof(Translate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx1.
        /// </summary>
        public static string xxx {
            get {
                return ResourceManager.GetString("xxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hola.
        /// </summary>
        public static string ⲀmainwindowⳭButton_EtⳭContentⲱ {
            get {
                return ResourceManager.GetString("ⲀmainwindowⳭButton_EtⳭContentⲱ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string ⲀmainwindowⳭLabel_LabelⳭContentⲱ {
            get {
                return ResourceManager.GetString("ⲀmainwindowⳭLabel_LabelⳭContentⲱ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello.
        /// </summary>
        public static string ⲀmainwindowⳭMessage_boxⳭShowⲱ {
            get {
                return ResourceManager.GetString("ⲀmainwindowⳭMessage_boxⳭShowⲱ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlock.
        /// </summary>
        public static string ⲀmainwindowⳭTextBlock_TextBlockⳭTextⲱ {
            get {
                return ResourceManager.GetString("ⲀmainwindowⳭTextBlock_TextBlockⳭTextⲱ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainWindow.
        /// </summary>
        public static string ⲀmainwindowⳭWindow_MainWindowⳭTitleⲱ {
            get {
                return ResourceManager.GetString("ⲀmainwindowⳭWindow_MainWindowⳭTitleⲱ", resourceCulture);
            }
        }
    }
}
